name: Prepare tag name
description: Prepare the tag name given a WordPress version number

inputs:
  tag:
    description: Tag name for WordPress release
    required: true
    type: string
outputs:
  short:
    description: Short tag name, eg 6.7 or 6.7.1
    value: ${{ steps.tag.outputs.short }}
  long:
    description: Long tag name, eg. 6.7.0 or 6.7.1
    value: ${{ steps.tag.outputs.long }}
  branch:
    description: Branch number, eg. 6.7
    value: ${{ steps.tag.outputs.branch }}

runs:
  using: composite
  steps:
    - name: Prepare tag name
      shell: bash
      id: tag
      run: | #shell
        LONG_TAG="${{ inputs.tag }}"
        echo short="${LONG_TAG%.0}" >> "$GITHUB_OUTPUT"
        echo long="$LONG_TAG" >> "$GITHUB_OUTPUT"
        echo branch="${LONG_TAG%.*}" >> "$GITHUB_OUTPUT"
