name: Verify file checksums

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  checksums:
    name: ${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 1
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true

      - name: Download checksums from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://api.wordpress.org/core/checksums/1.0/?version=${{ steps.tag.outputs.short }}
          output: checksums.json
          version: ${{ steps.tag.outputs.long }}

      - name: Download zip from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip
          output: wordpress-${{ steps.tag.outputs.short }}.zip
          version: ${{ steps.tag.outputs.long }}

      - name: Extract zip
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          unzip -q "wordpress-${TAG}.zip"

      - name: Convert checksums.json into format that can be used by md5sum
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          jq --raw-output --arg tag "$TAG" '.checksums[$tag] | to_entries[] | "\(.value)  \(.key)"' checksums.json > "checksums/${TAG}.md5"

      - name: Verify checksums
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          (cd wordpress && md5sum --check "../checksums/${TAG}.md5")

      - name: Create pull request if there are additions or changes
        if: github.ref == 'refs/heads/trunk'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          add-paths: checksums
          title: "Update checksums for WordPress ${{ steps.tag.outputs.short }}"
          body: "This pull request updates the checksums for WordPress ${{ steps.tag.outputs.short }}."
          branch: "checksums/${{ steps.tag.outputs.short }}"
          commit-message: "Update checksums for WordPress ${{ steps.tag.outputs.short }}"
          base: trunk
          delete-branch: true
