name: Verify file checksums

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  checksums:
    name: ${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Download checksums from wordpress.org
        run: | #shell
          wget -O checksums.json "https://api.wordpress.org/core/checksums/1.0/?version=${TAG}" \
            --user-agent="WordPress/${BRANCH}"
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}

      - name: Download and extract zip from wordpress.org
        run: | #shell
          wget "https://wordpress.org/wordpress-${TAG}.zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip -q "wordpress-${TAG}.zip"
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}

      - name: Convert checksums.json into format that can be used by md5sum
        run: | #shell
          jq -r --arg tag "$TAG" '.checksums[$tag] | to_entries[] | "\(.value)  wordpress/\(.key)"' checksums.json > checksums.md5
        env:
          TAG: ${{ steps.tag.outputs.short }}

      - name: Verify checksums
        run: | #shell
          md5sum -c checksums.md5
