name: Verify file checksums

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  checksums:
    name: ${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 10
    environment:
      name: checksums
      url: "https://api.wordpress.org/core/checksums/1.0/?version=${{ steps.tag.outputs.short }}"
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true

      - name: Download checksums from wordpress.org
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          wget --output-document=checksums.json "https://api.wordpress.org/core/checksums/1.0/?version=${TAG}" \
            --user-agent="WordPress/${TAG}"

      - name: Download and extract zip from wordpress.org
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          wget "https://wordpress.org/wordpress-${TAG}.zip" \
            --user-agent="WordPress/${TAG}"
          unzip -q "wordpress-${TAG}.zip"

      - name: Convert checksums.json into format that can be used by md5sum
        env:
          MAJOR: ${{ steps.tag.outputs.major }}
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          mkdir -p "checksums/${MAJOR}"
          jq --raw-output --arg tag "$TAG" '.checksums[$tag] | to_entries[] | "\(.value)  \(.key)"' checksums.json > "checksums/${MAJOR}/${TAG}.md5"

      - name: Verify checksums
        env:
          MAJOR: ${{ steps.tag.outputs.major }}
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          (cd wordpress && md5sum --check="../checksums/${MAJOR}/${TAG}.md5")

      - name: Create pull request if there are additions or changes
        if: github.ref == 'refs/heads/trunk'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          add-paths: checksums
          title: "Update checksums for WordPress ${{ steps.tag.outputs.short }}"
          body: "This pull request updates the checksums for WordPress ${{ steps.tag.outputs.short }}."
          branch: "checksums/${{ steps.tag.outputs.short }}"
          commit-message: "Update checksums for WordPress ${{ steps.tag.outputs.short }}"
          base: trunk
          delete-branch: true
