name: Verify file checksums

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions:
  contents: read

jobs:
  checksums:
    name: ${{ inputs.tag }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        run: |
          export LONG_TAG="${{ inputs.tag }}"
          export SHORT_TAG="${LONG_TAG%.0}"
          export BRANCH_NUMBER="${LONG_TAG%.*}"
          echo "short=$SHORT_TAG" >> "$GITHUB_OUTPUT"
          echo "long=$LONG_TAG" >> "$GITHUB_OUTPUT"
          echo "branch=$BRANCH_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Download checksums from wordpress.org
        run: |
          wget -O checksums.json "https://api.wordpress.org/core/checksums/1.0/?version=${{ steps.tag.outputs.short }}" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"

      - name: Download and extract zip from wordpress.org
        run: |
          wget "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"
          unzip -q wordpress-${{ steps.tag.outputs.short }}.zip

      - name: Convert checksums.json into format that can be used by md5sum
        run: |
          jq -r '.checksums."${{ steps.tag.outputs.short }}" | to_entries[] | "\(.value)  wordpress/\(.key)"' checksums.json > checksums.md5

      - name: Verify checksums
        run: |
          md5sum -c checksums.md5
