name: Verify file checksums

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  checksums:
    name: ${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required to push the branch
      pull-requests: write # Required to create a pull request
    timeout-minutes: 1
    steps:
      - name: Prepare tag name
        id: tag
        uses: $/.github/actions/prepare-tag-name
        with:
          tag: ${{ inputs.tag }}

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download checksums from wordpress.org
        uses: johnbillion/plugin-infrastructure/actions/download-with-retry@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
        with:
          url: https://api.wordpress.org/core/checksums/1.0/?version=${{ steps.tag.outputs.short }}
          output: checksums.json

      - name: Download zip from wordpress.org
        uses: johnbillion/plugin-infrastructure/actions/download-with-retry@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip
          output: wordpress-${{ steps.tag.outputs.short }}.zip

      - name: Extract zip
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          unzip -q "wordpress-${TAG}.zip"

      - name: Convert checksums.json into format that can be used by md5sum
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          jq --raw-output --arg tag "$TAG" '.checksums[$tag] | to_entries[] | "\(.value)  \(.key)"' checksums.json > "checksums/${TAG}.md5"

      - name: Verify checksums
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          (cd wordpress && md5sum --check "../checksums/${TAG}.md5")

      - name: Create pull request if there are additions or changes
        if: github.ref == 'refs/heads/trunk'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1 # zizmor: ignore[superfluous-actions]
        with:
          add-paths: checksums
          title: "Update checksums for WordPress ${{ steps.tag.outputs.short }}"
          body: "This pull request updates the checksums for WordPress ${{ steps.tag.outputs.short }}."
          branch: "checksums/${{ steps.tag.outputs.short }}"
          commit-message: "Update checksums for WordPress ${{ steps.tag.outputs.short }}"
          base: trunk
          delete-branch: true
