name: Compare sources

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string
      source:
        description: Source for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  compare:
    name: "${{ inputs.source }}"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Download canonical source artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # 4.1.8
        with:
          name: wordpress-${{ inputs.tag }}-develop.svn.wordpress.org
          path: develop.svn.wordpress.org

      - name: Download comparison source artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # 4.1.8
        with:
          name: wordpress-${{ inputs.tag }}-${{ inputs.source }}
          path: ${{ inputs.source }}

      - name: Compare files
        env:
          SOURCE: ${{ inputs.source }}
        run: | #shell
          diff --strip-trailing-cr --recursive develop.svn.wordpress.org "${SOURCE}"
