name: Compare sources

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string
      source:
        description: Source for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  compare:
    name: "${{ inputs.source }}"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 1
    steps:
      - name: Download canonical source artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: wordpress-${{ inputs.tag }}-develop.svn.wordpress.org
          path: develop.svn.wordpress.org

      - name: Download comparison source artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: wordpress-${{ inputs.tag }}-${{ inputs.source }}
          path: ${{ inputs.source }}

      - name: Remove files erroneously shipped in WordPress 7.0
        env:
          TAG: ${{ inputs.tag }}
          SOURCE: ${{ inputs.source }}
        run: | #shell
          if dpkg --compare-versions "${TAG}" ge "7.0"; then
            rm -rf "${SOURCE}/wp-includes/collaboration"
            rm -f "${SOURCE}/wp-includes/collaboration.php"
            rm -f "${SOURCE}/wp-includes/js/dist/sync.js"
            rm -f "${SOURCE}/wp-includes/js/dist/sync.min.js"
          fi

      - name: Compare files
        env:
          SOURCE: ${{ inputs.source }}
        run: | #shell
          diff --strip-trailing-cr --recursive --color=always develop.svn.wordpress.org "${SOURCE}"
