name: Fetch build

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string
      build:
        description: Build name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  reproduce:
    name: "${{ inputs.build }}"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Git checkout core.git.wordpress.org
        if: inputs.build == 'core.git.wordpress.org'
        env:
          TAG: ${{ steps.tag.outputs.long }}
        run: | #shell
          git clone --depth 1 --branch "${TAG}" git://core.git.wordpress.org/ .

      - name: SVN checkout core.svn.wordpress.org
        if: inputs.build == 'core.svn.wordpress.org'
        uses: johnbillion/rave-wordpress/.github/actions/svn-with-retry@trunk
        with:
          url: https://core.svn.wordpress.org/tags/${{ steps.tag.outputs.short }}/

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: wordpress-${{ steps.tag.outputs.long }}-${{ inputs.build }}
          path: .
          if-no-files-found: error
