name: Verify package hashes

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  zip-md5:
    name: Zip MD5
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Download zip from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip
          output: package.zip

      - name: Download MD5 hash from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip.md5
          output: package.zip.md5

      - name: Check the MD5 hash
        run: | #shell
          echo "$(cat package.zip.md5) package.zip" | md5sum --check -

  zip-sha1:
    name: Zip SHA-1
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Download zip from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip
          output: package.zip

      - name: Download SHA-1 hash from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip.sha1
          output: package.zip.sha1

      - name: Check the SHA-1 hash
        run: | #shell
          echo "$(cat package.zip.sha1) package.zip" | sha1sum --check -

  tar-md5:
    name: Tar MD5
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Download tar.gz from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz
          output: package.tar.gz

      - name: Download MD5 hash from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz.md5
          output: package.tar.gz.md5

      - name: Check the MD5 hash
        run: | #shell
          echo "$(cat package.tar.gz.md5) package.tar.gz" | md5sum --check -

  tar-sha1:
    name: Tar SHA-1
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Download tar.gz from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz
          output: package.tar.gz

      - name: Download SHA-1 hash from wordpress.org
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz.sha1
          output: package.tar.gz.sha1

      - name: Check the SHA-1 hash
        run: | #shell
          echo "$(cat package.tar.gz.sha1) package.tar.gz" | sha1sum --check -
