name: Verify package hashes

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions:
  contents: read

jobs:
  zip:
    name: "${{ inputs.tag }} zip hashes"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        run: |
          export LONG_TAG="${{ inputs.tag }}"
          export SHORT_TAG="${LONG_TAG%.0}"
          export BRANCH_NUMBER="${LONG_TAG%.*}"
          echo "short=$SHORT_TAG" >> "$GITHUB_OUTPUT"
          echo "long=$LONG_TAG" >> "$GITHUB_OUTPUT"
          echo "branch=$BRANCH_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Download zip and hashes from wordpress.org
        run: |
          wget -O package.zip "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip"
          wget -O package.zip.md5 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip.md5"
          wget -O package.zip.sha1 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip.sha1"

      - name: Check the md5 hash
        run: |
          echo "$(cat package.zip.md5) package.zip" | md5sum -c -

      - name: Check the sha1 hash
        run: |
          echo "$(cat package.zip.sha1) package.zip" | sha1sum -c -
  tar:
    name: "${{ inputs.tag }} tar hashes"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        run: |
          export LONG_TAG="${{ inputs.tag }}"
          export SHORT_TAG="${LONG_TAG%.0}"
          export BRANCH_NUMBER="${LONG_TAG%.*}"
          echo "short=$SHORT_TAG" >> "$GITHUB_OUTPUT"
          echo "long=$LONG_TAG" >> "$GITHUB_OUTPUT"
          echo "branch=$BRANCH_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Download tar.gz and hashes from wordpress.org
        run: |
          wget -O package.tar.gz "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz"
          wget -O package.tar.gz.md5 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz.md5"
          wget -O package.tar.gz.sha1 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz.sha1"

      - name: Check the md5 hash
        run: |
          echo "$(cat package.tar.gz.md5) package.tar.gz" | md5sum -c -

      - name: Check the sha1 hash
        run: |
          echo "$(cat package.tar.gz.sha1) package.tar.gz" | sha1sum -c -
