name: Verify package hashes

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  zip:
    name: "${{ inputs.tag }} zip"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: ./.github/actions/prepare-tag-name

      - name: Download zip and hashes from wordpress.org
        run: |
          wget -O package.zip "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"
          wget -O package.zip.md5 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip.md5" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"
          wget -O package.zip.sha1 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip.sha1" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"

      - name: Check the md5 hash
        run: |
          echo "$(cat package.zip.md5) package.zip" | md5sum -c -

      - name: Check the sha1 hash
        run: |
          echo "$(cat package.zip.sha1) package.zip" | sha1sum -c -

  tar:
    name: "${{ inputs.tag }} tar"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: ./.github/actions/prepare-tag-name

      - name: Download tar.gz and hashes from wordpress.org
        run: |
          wget -O package.tar.gz "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"
          wget -O package.tar.gz.md5 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz.md5" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"
          wget -O package.tar.gz.sha1 "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz.sha1" \
            --user-agent="WordPress/${{ steps.tag.outputs.branch }}"

      - name: Check the md5 hash
        run: |
          echo "$(cat package.tar.gz.md5) package.tar.gz" | md5sum -c -

      - name: Check the sha1 hash
        run: |
          echo "$(cat package.tar.gz.sha1) package.tar.gz" | sha1sum -c -
