# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Lint
on:
  pull_request:
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'
  push:
    branches:
      - trunk
    paths:
      # Only run when changes are made to workflow files.
      - '.github/workflows/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-workflow-lint.yml@1264303fa2e8b81ac9b49265cd96c96947eaacd0
