name: Verify the update offers

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  verify:
    name: ${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # 4.1.8
        with:
          name: offers

      - name: Verify the offer URLs
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: | #shell
          EXPECTED_URL_FULL="https://downloads.w.org/release/wordpress-${TAG}.zip"
          EXPECTED_URL_NO_CONTENT="https://downloads.w.org/release/wordpress-${TAG}-no-content.zip"
          MATCHING_OBJECT=$(jq --arg tag "$TAG" '.[] | select(.version == $tag)' offers.json)

          if [ -z "$MATCHING_OBJECT" ]; then
            echo "No matching version found for tag $TAG"
            exit 1
          fi

          DOWNLOAD_URL=$(echo "$MATCHING_OBJECT" | jq --raw-output '.download')
          PACKAGE_URL=$(echo "$MATCHING_OBJECT" | jq --raw-output '.packages.full')
          NO_CONTENT_URL=$(echo "$MATCHING_OBJECT" | jq --raw-output '.packages.no_content')

          if [ "$DOWNLOAD_URL" != "$EXPECTED_URL_FULL" ]; then
            echo "Download URL $DOWNLOAD_URL does not match the expected $EXPECTED_URL_FULL"
            exit 1
          fi

          if [ "$PACKAGE_URL" != "$EXPECTED_URL_FULL" ]; then
            echo "Package URL $PACKAGE_URL does not match the expected $EXPECTED_URL_FULL"
            exit 1
          fi

          if [ "$NO_CONTENT_URL" != "$EXPECTED_URL_NO_CONTENT" ]; then
            echo "No-content URL $NO_CONTENT_URL does not match the expected $EXPECTED_URL_NO_CONTENT"
            exit 1
          fi
