name: Reproduce and verify packages

on:
  push:
    branches:
      - trunk
    paths:
      - .github/workflows/*
      - composer.json
  pull_request:
    branches:
      - '**'
    paths:
      - .github/workflows/*
      - composer.json
  schedule:
    # Hourly schedule.
    #
    #        ┌───────────── minute           (0 - 59)
    #        │  ┌────────── hour             (0 - 23)
    #        │  │  ┌─────── day of the month (1 - 31)
    #        │  │  │  ┌──── month            (1 - 12 or JAN-DEC)
    #        │  │  │  │  ┌─ day of the week  (0 - 6 or SUN-SAT)
    #        │  │  │  │  │
    #        │  │  │  │  │
    #        │  │  │  │  │
    - cron: '0  *  *  *  *'
  workflow_dispatch:
    inputs:
      version:
        description: Tag name for WordPress release. Use `x.y` for majors and `x.y.z` for minors.
        required: true
        type: string

permissions:
  contents: read

jobs:
  versions:
    name: Determine latest branch numbers
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.fetch.outputs.versions }}
    steps:
      - name: Fetch versions matrix from API data
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: | #shell
          # Fetches the version number from the first three objects which have a `response` of `autoupdate`
          versions=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -c '.offers | map(select(.response == "autoupdate")) | .[0:3] | map(.version)')
          # Map each version and if the number is in major.minor syntax, append a .0
          versions=$(echo $versions | jq -c 'map(. | capture("(?<major>\\d+)\\.(?<minor>\\d+)(\\.(?<patch>\\d+))?") | .major + "." + .minor + "." + (.patch // "0") )')
          echo "$versions" > versions.json
      - name: Fetch version matrix from workflow input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: | #shell
          echo '["${{ inputs.version }}"]' > versions.json
      - name: Output versions from versions.json
        id: fetch
        run: | #shell
          echo "versions=$(cat versions.json)" >> "$GITHUB_OUTPUT"
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: versions
          path: versions.json
  reproduce:
    name: "Reproduce ${{ matrix.tag }}"
    needs:
      - versions
    strategy:
      matrix:
        tag: ${{ fromJson(needs.versions.outputs.versions) }}
        source:
          - develop.svn.wordpress.org
          - develop.git.wordpress.org
          - github-wordpress-develop
          - core.trac.wordpress.org
      fail-fast: false
    uses: ./.github/workflows/reproduce.yml
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
  compare:
    name: "Compare ${{ matrix.tag }}"
    needs:
      - reproduce
      - versions
    strategy:
      matrix:
        tag: ${{ fromJson(needs.versions.outputs.versions) }}
        source:
          - develop.git.wordpress.org
          - github-wordpress-develop
          - core.trac.wordpress.org
      fail-fast: false
    uses: ./.github/workflows/compare.yml
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
  verify-packages:
    name: "Verify ${{ matrix.tag }} packages"
    needs:
      - reproduce
      - versions
    strategy:
      matrix:
        tag: ${{ fromJson(needs.versions.outputs.versions) }}
        package:
          - wordpress.org-zip
          - wordpress.org-tar
          - downloads.wordpress.org-zip
          - downloads.wordpress.org-tar
          - build.trac.wordpress.org
          - github-zip
          - github-tar
          - roots-wordpress-full
          - johnpbloch-wordpress
      fail-fast: false
    uses: ./.github/workflows/verify.yml
    with:
      tag: ${{ matrix.tag }}
      package: ${{ matrix.package }}
  verify-latest-package:
    name: "Verify ${{ matrix.tag }} packages"
    needs:
      - reproduce
    strategy:
      matrix:
        tag:
          - 'latest'
        package:
          - wordpress.org-zip
          - wordpress.org-tar
      fail-fast: false
    uses: ./.github/workflows/verify.yml
    with:
      tag: ${{ matrix.tag }}
      package: ${{ matrix.package }}
  verify-hashes:
    name: "Verify ${{ matrix.tag }} hashes"
    needs:
      - versions
    strategy:
      matrix:
        tag: ${{ fromJson(needs.versions.outputs.versions) }}
      fail-fast: false
    uses: ./.github/workflows/hashes.yml
    with:
      tag: ${{ matrix.tag }}
  verify-checksums:
    name: "Verify ${{ matrix.tag }} checksums"
    needs:
      - versions
    strategy:
      matrix:
        tag: ${{ fromJson(needs.versions.outputs.versions) }}
      fail-fast: false
    uses: ./.github/workflows/checksums.yml
    with:
      tag: ${{ matrix.tag }}
