name: Verify package

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string
      package:
        description: Package for WordPress release
        required: true
        type: string

permissions:
  contents: read

jobs:
  verify:
    name: "${{ inputs.package }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        run: |
          export LONG_TAG="${{ inputs.tag }}"
          export SHORT_TAG="${LONG_TAG%.0}"
          export BRANCH_NUMBER="${LONG_TAG%.*}"
          echo "short=$SHORT_TAG" >> "$GITHUB_OUTPUT"
          echo "long=$LONG_TAG" >> "$GITHUB_OUTPUT"
          echo "branch=$BRANCH_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        if: inputs.tag != 'latest'
        uses: actions/download-artifact@v4
        with:
          name: wordpress-${{ steps.tag.outputs.long }}-develop.svn.wordpress.org
          path: source

      - name: Download versions artifact
        if: inputs.tag == 'latest'
        uses: actions/download-artifact@v4
        with:
          name: versions

      - name: Extract the latest version number from versions.json
        if: inputs.tag == 'latest'
        id: extract
        run: |
          echo "latest=$(jq -r '.[0]' versions.json)" >> "$GITHUB_OUTPUT"

      - name: Download latest artifact
        if: inputs.tag == 'latest'
        uses: actions/download-artifact@v4
        with:
          name: "wordpress-${{ steps.extract.outputs.latest }}-develop.svn.wordpress.org"
          path: source

      - name: Get zip file from GitHub
        if: inputs.package == 'github-zip'
        run: |
          wget -O package.zip "https://github.com/WordPress/WordPress/archive/refs/tags/${{ steps.tag.outputs.short }}.zip"
          unzip package.zip -d wordpress
          mv wordpress/WordPress-${{ steps.tag.outputs.short }} package

      - name: Get tar file from GitHub
        if: inputs.package == 'github-tar'
        run: |
          wget -O package.tar.gz "https://github.com/WordPress/WordPress/archive/refs/tags/${{ steps.tag.outputs.short }}.tar.gz"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/WordPress-${{ steps.tag.outputs.short }} package

      - name: Get zip file from wordpress.org
        if: inputs.package == 'wordpress.org-zip' && inputs.tag != 'latest'
        run: |
          wget -O package.zip "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.zip"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get tar file from wordpress.org
        if: inputs.package == 'wordpress.org-tar' && inputs.tag != 'latest'
        run: |
          wget -O package.tar.gz "https://wordpress.org/wordpress-${{ steps.tag.outputs.short }}.tar.gz"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Get latest zip file from wordpress.org
        if: inputs.package == 'wordpress.org-zip' && inputs.tag == 'latest'
        run: |
          wget -O package.zip "https://wordpress.org/latest.zip"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get latest tar file from wordpress.org
        if: inputs.package == 'wordpress.org-tar' && inputs.tag == 'latest'
        run: |
          wget -O package.tar.gz "https://wordpress.org/latest.tar.gz"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Get zip file from downloads.wordpress.org
        if: inputs.package == 'downloads.wordpress.org-zip'
        run: |
          wget -O package.zip "https://downloads.wordpress.org/release/wordpress-${{ steps.tag.outputs.short }}.zip"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get tar file from downloads.wordpress.org
        if: inputs.package == 'downloads.wordpress.org-tar'
        run: |
          wget -O package.tar.gz "https://downloads.wordpress.org/release/wordpress-${{ steps.tag.outputs.short }}.tar.gz"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Get zip file from downloads.w.org
        if: inputs.package == 'downloads.w.org-zip'
        run: |
          wget -O package.zip "https://downloads.w.org/release/wordpress-${{ steps.tag.outputs.short }}.zip"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get tar file from downloads.w.org
        if: inputs.package == 'downloads.w.org-tar'
        run: |
          wget -O package.tar.gz "https://downloads.w.org/release/wordpress-${{ steps.tag.outputs.short }}.tar.gz"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Download zip from build.trac.wordpress.org
        if: inputs.package == 'build.trac.wordpress.org'
        run: |
          wget -O package.zip "https://build.trac.wordpress.org/browser/tags/${{ steps.tag.outputs.short }}?format=zip"
          unzip package.zip -d wordpress
          mv wordpress/${{ steps.tag.outputs.short }} package

      - name: Download Docker image
        if: inputs.package == 'docker-wordpress'
        run: |
          mkdir package
          docker run -d \
            -v ./package:/var/www/html \
            "wordpress:${{ steps.tag.outputs.long }}"

      - name: Download zip from core-updates.wpengine.com
        if: inputs.package == 'wpengine-zip'
        run: |
          wget -O package.zip "https://core-updates.wpengine.com/wordpress-${{ steps.tag.outputs.short }}.zip"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Download roots/wordpress-full
        if: inputs.package == 'roots-wordpress-full'
        run: |
          composer require "roots/wordpress-full:${{ steps.tag.outputs.long }}" --prefer-dist --no-progress --no-suggest
          mv vendor/roots/wordpress-full package

      - name: Download johnpbloch/wordpress
        if: inputs.package == 'johnpbloch-wordpress'
        run: |
          composer require "johnpbloch/wordpress:${{ steps.tag.outputs.long }}" --prefer-dist --no-progress --no-suggest
          mv wordpress package
          rm package/composer.json

      - name: Handle anomalies with build files in TT and TT1
        if: inputs.package == 'github-zip' || inputs.package == 'github-tar' || inputs.package == 'build.trac.wordpress.org'
        run: |
          rm package/wp-content/themes/twentytwenty/.npmrc
          rm package/wp-content/themes/twentytwenty/.stylelintrc.json
          rm package/wp-content/themes/twentytwentyone/.npmrc
          rm package/wp-content/themes/twentytwentyone/.stylelintignore
          rm package/wp-content/themes/twentytwentyone/.stylelintrc-css.json
          rm package/wp-content/themes/twentytwentyone/.stylelintrc.json

      - name: Handle known differences in bundled themes
        if: inputs.package != 'github-zip' && inputs.package != 'github-tar' && inputs.package != 'build.trac.wordpress.org'
        run: |
          rm -rf source/wp-content/themes/twentyten
          rm -rf source/wp-content/themes/twentyeleven
          rm -rf source/wp-content/themes/twentytwelve
          rm -rf source/wp-content/themes/twentythirteen
          rm -rf source/wp-content/themes/twentyfourteen
          rm -rf source/wp-content/themes/twentyfifteen
          rm -rf source/wp-content/themes/twentysixteen
          rm -rf source/wp-content/themes/twentyseventeen
          if [[ "${{ inputs.tag }}" == "latest" ]] || (( $(echo "${{ steps.tag.outputs.branch }} >= 6.4" | bc -l) )); then
            rm -rf source/wp-content/themes/twentynineteen
            rm -rf source/wp-content/themes/twentytwenty
            rm -rf source/wp-content/themes/twentytwentyone
          fi
          if [[ "${{ inputs.tag }}" == "latest" ]] || (( $(echo "${{ steps.tag.outputs.branch }} >= 6.7" | bc -l) )); then
            rm -rf source/wp-content/themes/twentytwentytwo
          fi

      - name: Handle known differences in bundled plugins
        run: |
          rm -rf package/wp-content/plugins/akismet

      - name: Tree source
        run: |
          tree source || true

      - name: Tree package
        run: |
          tree package || true

      - name: Compare files
        run: |
          diff --strip-trailing-cr --recursive source package
