name: Verify package

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string
      package:
        description: Package for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  verify:
    name: "${{ inputs.package }}"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Download artifact
        if: inputs.tag != 'latest'
        uses: actions/download-artifact@v4
        with:
          name: wordpress-${{ steps.tag.outputs.long }}-develop.svn.wordpress.org
          path: source

      - name: Download versions artifact
        if: inputs.tag == 'latest'
        uses: actions/download-artifact@v4
        with:
          name: versions

      - name: Extract the latest version number from versions.json
        if: inputs.tag == 'latest'
        id: extract
        run: | #shell
          echo latest="$(jq -r '.[0]' versions.json)" >> "$GITHUB_OUTPUT"

      - name: Download latest artifact
        if: inputs.tag == 'latest'
        uses: actions/download-artifact@v4
        with:
          name: "wordpress-${{ steps.extract.outputs.latest }}-develop.svn.wordpress.org"
          path: source

      - name: Get zip file from GitHub
        if: inputs.package == 'github-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.zip "https://github.com/WordPress/WordPress/archive/refs/tags/${TAG}.zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip package.zip -d wordpress
          mv "wordpress/WordPress-${TAG}" package

      - name: Get tar file from GitHub
        if: inputs.package == 'github-tar'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.tar.gz "https://github.com/WordPress/WordPress/archive/refs/tags/${TAG}.tar.gz" \
            --user-agent="WordPress/${BRANCH}"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv "wordpress/WordPress-${TAG}" package

      - name: Get zip file from wordpress.org
        if: inputs.package == 'wordpress.org-zip' && inputs.tag != 'latest'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.zip "https://wordpress.org/wordpress-${TAG}.zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get tar file from wordpress.org
        if: inputs.package == 'wordpress.org-tar' && inputs.tag != 'latest'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.tar.gz "https://wordpress.org/wordpress-${TAG}.tar.gz" \
            --user-agent="WordPress/${BRANCH}"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Get latest zip file from wordpress.org
        if: inputs.package == 'wordpress.org-zip' && inputs.tag == 'latest'
        env:
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.zip "https://wordpress.org/latest.zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get latest tar file from wordpress.org
        if: inputs.package == 'wordpress.org-tar' && inputs.tag == 'latest'
        env:
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.tar.gz "https://wordpress.org/latest.tar.gz" \
            --user-agent="WordPress/${BRANCH}"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Get zip file from downloads.wordpress.org
        if: inputs.package == 'downloads.wordpress.org-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.zip "https://downloads.wordpress.org/release/wordpress-${TAG}.zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get tar file from downloads.wordpress.org
        if: inputs.package == 'downloads.wordpress.org-tar'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.tar.gz "https://downloads.wordpress.org/release/wordpress-${TAG}.tar.gz" \
            --user-agent="WordPress/${BRANCH}"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Get zip file from downloads.w.org
        if: inputs.package == 'downloads.w.org-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.zip "https://downloads.w.org/release/wordpress-${TAG}.zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Get tar file from downloads.w.org
        if: inputs.package == 'downloads.w.org-tar'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.tar.gz "https://downloads.w.org/release/wordpress-${TAG}.tar.gz" \
            --user-agent="WordPress/${BRANCH}"
          mkdir wordpress
          tar -xzf package.tar.gz -C wordpress
          mv wordpress/wordpress package

      - name: Download zip from build.trac.wordpress.org
        if: inputs.package == 'build.trac.wordpress.org'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.zip "https://build.trac.wordpress.org/browser/tags/${TAG}?format=zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip package.zip -d wordpress
          mv "wordpress/${TAG}" package

      - name: Download Docker image
        if: inputs.package == 'docker-wordpress'
        env:
          WP_VERSION: ${{ steps.tag.outputs.long }}
        run: | #shell
          docker compose up -d wordpress
          docker compose run --rm wordpress -- rm /var/www/html/.htaccess
          docker compose run --rm wordpress -- rm /var/www/html/wp-config-docker.php
          docker compose run --rm wordpress -- rm -r /var/www/html/wp-content/plugins/akismet

      - name: Download zip from core-updates.wpengine.com
        if: inputs.package == 'wpengine-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          wget -O package.zip "https://core-updates.wpengine.com/wordpress-${TAG}.zip" \
            --user-agent="WordPress/${BRANCH}"
          unzip package.zip -d wordpress
          mv wordpress/wordpress package

      - name: Download roots/wordpress-full
        if: inputs.package == 'roots-wordpress-full'
        env:
          TAG: ${{ steps.tag.outputs.long }}
        run: | #shell
          composer require "roots/wordpress-full:${TAG}" --prefer-dist --no-progress
          mv vendor/roots/wordpress-full package

      - name: Download johnpbloch/wordpress
        if: inputs.package == 'johnpbloch-wordpress'
        env:
          TAG: ${{ steps.tag.outputs.long }}
        run: | #shell
          composer require "johnpbloch/wordpress:${TAG}" --prefer-dist --no-progress --no-plugins
          mv vendor/johnpbloch/wordpress-core package
          rm package/composer.json

      - name: Handle anomalies with build files in TT and TT1
        if: inputs.package == 'github-zip' || inputs.package == 'github-tar' || inputs.package == 'build.trac.wordpress.org'
        run: | #shell
          rm package/wp-content/themes/twentytwenty/.npmrc
          rm package/wp-content/themes/twentytwenty/.stylelintrc.json
          rm package/wp-content/themes/twentytwentyone/.npmrc
          rm package/wp-content/themes/twentytwentyone/.stylelintignore
          rm package/wp-content/themes/twentytwentyone/.stylelintrc-css.json
          rm package/wp-content/themes/twentytwentyone/.stylelintrc.json

      - name: Handle known differences in bundled themes
        if: inputs.package != 'github-zip' && inputs.package != 'github-tar' && inputs.package != 'build.trac.wordpress.org'
        env:
          TAG: ${{ inputs.tag }}
          BRANCH: ${{ steps.tag.outputs.branch }}
        run: | #shell
          rm -rf source/wp-content/themes/twentyten
          rm -rf source/wp-content/themes/twentyeleven
          rm -rf source/wp-content/themes/twentytwelve
          rm -rf source/wp-content/themes/twentythirteen
          rm -rf source/wp-content/themes/twentyfourteen
          rm -rf source/wp-content/themes/twentyfifteen
          rm -rf source/wp-content/themes/twentysixteen
          rm -rf source/wp-content/themes/twentyseventeen
          if [[ "${TAG}" == "latest" ]] || (( $(echo "${BRANCH} >= 6.4" | bc -l) )); then
            rm -rf source/wp-content/themes/twentynineteen
            rm -rf source/wp-content/themes/twentytwenty
            rm -rf source/wp-content/themes/twentytwentyone
          fi
          if [[ "${TAG}" == "latest" ]] || (( $(echo "${BRANCH} >= 6.7" | bc -l) )); then
            rm -rf source/wp-content/themes/twentytwentytwo
          fi

      - name: Handle known differences in bundled plugins
        run: | #shell
          rm -rf package/wp-content/plugins/akismet

      - name: Tree source
        run: | #shell
          tree source || true

      - name: Tree package
        run: | #shell
          tree package || true

      - name: Compare files
        run: | #shell
          diff --strip-trailing-cr --recursive source package
