name: Verify distributed versions

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string
      package:
        description: Package for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  verify:
    name: "${{ inputs.package }}"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Verify versions distributed by GitHub
        if: inputs.package == 'github-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          latest_tag=$(gh api repos/WordPress/WordPress/tags --jq '.[0].name')
          if [ "$latest_tag" != "$TAG" ]; then
            echo "Error: Found a newer tag ($latest_tag) than $TAG"
            exit 1
          fi

      - name: Fetch roots/wordpress-full versions
        if: inputs.package == 'roots-wordpress-full'
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://repo.packagist.org/p2/roots/wordpress-full.json
          output: roots-wordpress-full.json
          version: ${{ steps.tag.outputs.long }}

      - name: Verify versions distributed by roots/wordpress-full
        if: inputs.package == 'roots-wordpress-full'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output '.packages["roots/wordpress-full"] | map(.version) | .[]' roots-wordpress-full.json | grep -Ev -- '-(RC|rc|beta|alpha|dev)' | sort -V | tail -n1)
          if [ "$latest_version" != "$TAG" ]; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi

      - name: Fetch johnpbloch/wordpress versions
        if: inputs.package == 'johnpbloch-wordpress'
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://repo.packagist.org/p2/johnpbloch/wordpress.json
          output: johnpbloch-wordpress.json
          version: ${{ steps.tag.outputs.long }}

      - name: Verify versions distributed by johnpbloch/wordpress
        if: inputs.package == 'johnpbloch-wordpress'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output '.packages["johnpbloch/wordpress"] | map(.version) | sort_by(.) | last' johnpbloch-wordpress.json)
          if [ "$latest_version" != "$TAG" ]; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi

      - name: Verify versions distributed by Docker
        if: inputs.package == 'docker-wordpress'
        env:
          TAG: ${{ steps.tag.outputs.long }}
        run: |
          set -e

          page=1
          all_tags=""

          while [ $page -le 3 ]; do  # Fetch 3 pages to find stable tags
            tags=$(curl -s "https://hub.docker.com/v2/repositories/library/wordpress/tags?page_size=100&page=$page" | jq --raw-output '.results[].name')

            all_tags="$all_tags$tags"$'\n'

            page=$((page + 1))
          done

          latest_tag=$(echo "$all_tags" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)

          if [ "$latest_tag" != "$TAG" ]; then
            echo "Error: Found a newer tag ($latest_tag) than $TAG"
            exit 1
          fi

      - name: Fetch AspireCloud versions
        if: inputs.package == 'aspirecloud-zip'
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://api.aspirecloud.net/core/version-check/1.7/
          output: aspirecloud-versions.json
          version: ${{ steps.tag.outputs.long }}

      - name: Verify versions distributed by AspireCloud
        if: inputs.package == 'aspirecloud-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output '.offers[].version' aspirecloud-versions.json | sort -V | tail -n1)
          if [ "$latest_version" != "$TAG" ]; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi

      - name: Verify versions distributed by FAIR
        if: inputs.package == 'fair-zip'
        env:
          TAG: ${{ steps.tag.outputs.next }}
        run: |
          set -e
          url="https://github.com/fairpm/fair-plugin/releases/latest/download/wordpress-${TAG}-fair.zip"
          status=$(curl -L -o /dev/null -s -w "%{http_code}" "$url")
          if [ "$status" != "404" ]; then
            echo "Error: Found a release for next version ($TAG) at $url"
            exit 1
          fi

      - name: Verify versions distributed by WPEngine
        if: inputs.package == 'wpengine-zip'
        env:
          TAG: ${{ steps.tag.outputs.next }}
        run: |
          set -e
          url="https://core-updates.wpengine.com/wordpress-${TAG}.zip"
          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
          if [ "$status" != "404" ]; then
            echo "Error: Found a release for next version ($TAG) at $url"
            exit 1
          fi

      - name: Verify versions distributed by wordpress.org (zip)
        if: inputs.package == 'wordpress.org-zip'
        env:
          TAG: ${{ steps.tag.outputs.next }}
        run: |
          set -e
          url="https://wordpress.org/wordpress-${TAG}.zip"
          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
          if [ "$status" != "404" ]; then
            echo "Error: Found a release for next version ($TAG) at $url"
            exit 1
          fi

      - name: Verify versions distributed by wordpress.org (tar)
        if: inputs.package == 'wordpress.org-tar'
        env:
          TAG: ${{ steps.tag.outputs.next }}
        run: |
          set -e
          url="https://wordpress.org/wordpress-${TAG}.tar.gz"
          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
          if [ "$status" != "404" ]; then
            echo "Error: Found a release for next version ($TAG) at $url"
            exit 1
          fi

      - name: Verify versions distributed by downloads.wordpress.org (zip)
        if: inputs.package == 'downloads.wordpress.org-zip'
        env:
          TAG: ${{ steps.tag.outputs.next }}
        run: |
          set -e
          url="https://downloads.wordpress.org/release/wordpress-${TAG}.zip"
          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
          if [ "$status" != "404" ]; then
            echo "Error: Found a release for next version ($TAG) at $url"
            exit 1
          fi

      - name: Verify versions distributed by downloads.wordpress.org (tar)
        if: inputs.package == 'downloads.wordpress.org-tar'
        env:
          TAG: ${{ steps.tag.outputs.next }}
        run: |
          set -e
          url="https://downloads.wordpress.org/release/wordpress-${TAG}.tar.gz"
          status=$(curl -o /dev/null -s -w "%{http_code}" "$url")
          if [ "$status" != "404" ]; then
            echo "Error: Found a release for next version ($TAG) at $url"
            exit 1
          fi

      - name: Fetch stable-check data
        if: inputs.package == 'stable-check'
        uses: johnbillion/rave-wordpress/.github/actions/download-with-retry@trunk
        with:
          url: https://api.wordpress.org/core/stable-check/1.0/
          output: stable-check.json
          version: ${{ steps.tag.outputs.long }}

      - name: Verify the stable-check endpoint
        if: inputs.package == 'stable-check'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output 'to_entries[].key' stable-check.json | sort -V | tail -n1)
          if [ "$latest_version" != "$TAG" ]; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi
