name: Verify distributed versions

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name for WordPress release
        required: true
        type: string
      package:
        description: Package for WordPress release
        required: true
        type: string

permissions: {}

jobs:
  verify:
    name: "${{ inputs.package }}"
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 1
    steps:
      - name: Prepare tag name
        id: tag
        uses: johnbillion/rave-wordpress/.github/actions/prepare-tag-name@trunk
        with:
          tag: ${{ inputs.tag }}

      - name: Verify versions distributed by GitHub
        if: inputs.package == 'github-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          latest_tag=$(gh api repos/WordPress/WordPress/tags --jq '.[0].name')
          if dpkg --compare-versions "$latest_tag" gt "$TAG"; then
            echo "Error: Found a newer tag ($latest_tag) than $TAG"
            exit 1
          fi

      - name: Fetch roots/wordpress-full versions
        if: inputs.package == 'roots-wordpress-full'
        uses: johnbillion/plugin-infrastructure/actions/download-with-retry@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
        with:
          url: https://repo.packagist.org/p2/roots/wordpress-full.json
          output: roots-wordpress-full.json

      - name: Verify versions distributed by roots/wordpress-full
        if: inputs.package == 'roots-wordpress-full'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output '.packages["roots/wordpress-full"] | map(.version) | .[]' roots-wordpress-full.json | grep -Ev -- '-(RC|rc|beta|alpha|dev)' | sort -V | tail -n1)
          if dpkg --compare-versions "$latest_version" gt "$TAG"; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi

      - name: Fetch johnpbloch/wordpress versions
        if: inputs.package == 'johnpbloch-wordpress'
        uses: johnbillion/plugin-infrastructure/actions/download-with-retry@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
        with:
          url: https://repo.packagist.org/p2/johnpbloch/wordpress.json
          output: johnpbloch-wordpress.json

      - name: Verify versions distributed by johnpbloch/wordpress
        if: inputs.package == 'johnpbloch-wordpress'
        env:
          TAG: ${{ steps.tag.outputs.long }}
        run: |
          set -e
          latest_version=$(jq --raw-output '.packages["johnpbloch/wordpress"] | map(.version) | .[]' johnpbloch-wordpress.json | grep -Ev -- '-(RC|rc|beta|alpha|dev)' | sort -V | tail -n1)
          if dpkg --compare-versions "$latest_version" gt "$TAG"; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi

      - name: Fetch wp-core/wordpress versions
        if: inputs.package == 'wp-core-wordpress'
        uses: johnbillion/plugin-infrastructure/actions/download-with-retry@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
        with:
          url: https://api.wordpress.org/packages/p2/wp-core/wordpress.json
          output: wp-core-wordpress.json

      - name: Verify versions distributed by wp-core/wordpress
        if: inputs.package == 'wp-core-wordpress'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output '.packages["wp-core/wordpress"] | map(.version) | .[]' wp-core-wordpress.json | grep -Ev -- '-(RC|rc|beta|alpha|dev)' | sort -V | tail -n1)
          if dpkg --compare-versions "$latest_version" gt "$TAG"; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi

      - name: Fetch AspireCloud versions
        if: inputs.package == 'aspirecloud-zip'
        uses: johnbillion/plugin-infrastructure/actions/download-with-retry@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
        with:
          url: https://api.aspirecloud.net/core/version-check/1.7/
          output: aspirecloud-versions.json

      - name: Verify versions distributed by AspireCloud
        if: inputs.package == 'aspirecloud-zip'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output '.offers[].version' aspirecloud-versions.json | sort -V | tail -n1)
          if dpkg --compare-versions "$latest_version" gt "$TAG"; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi

      - name: Verify versions distributed by WPEngine
        if: inputs.package == 'wpengine-zip'
        uses: johnbillion/rave-wordpress/.github/actions/check-not-released@check-not-released
        with:
          url: https://core-updates.wpengine.com/wordpress-${{ steps.tag.outputs.next }}.zip
          version: ${{ steps.tag.outputs.long }}

      - name: Verify versions distributed by wordpress.org (zip)
        if: inputs.package == 'wordpress.org-zip'
        uses: johnbillion/rave-wordpress/.github/actions/check-not-released@check-not-released
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.next }}.zip
          version: ${{ steps.tag.outputs.long }}

      - name: Verify versions distributed by wordpress.org (tar)
        if: inputs.package == 'wordpress.org-tar'
        uses: johnbillion/rave-wordpress/.github/actions/check-not-released@check-not-released
        with:
          url: https://wordpress.org/wordpress-${{ steps.tag.outputs.next }}.tar.gz
          version: ${{ steps.tag.outputs.long }}

      - name: Verify versions distributed by downloads.wordpress.org (zip)
        if: inputs.package == 'downloads.wordpress.org-zip'
        uses: johnbillion/rave-wordpress/.github/actions/check-not-released@check-not-released
        with:
          url: https://downloads.wordpress.org/release/wordpress-${{ steps.tag.outputs.next }}.zip
          version: ${{ steps.tag.outputs.long }}

      - name: Verify versions distributed by downloads.wordpress.org (tar)
        if: inputs.package == 'downloads.wordpress.org-tar'
        uses: johnbillion/rave-wordpress/.github/actions/check-not-released@check-not-released
        with:
          url: https://downloads.wordpress.org/release/wordpress-${{ steps.tag.outputs.next }}.tar.gz
          version: ${{ steps.tag.outputs.long }}

      - name: Fetch stable-check data
        if: inputs.package == 'stable-check'
        uses: johnbillion/plugin-infrastructure/actions/download-with-retry@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
        with:
          url: https://api.wordpress.org/core/stable-check/1.0/
          output: stable-check.json

      - name: Verify the stable-check endpoint
        if: inputs.package == 'stable-check'
        env:
          TAG: ${{ steps.tag.outputs.short }}
        run: |
          set -e
          latest_version=$(jq --raw-output 'to_entries[].key' stable-check.json | sort -V | tail -n1)
          if dpkg --compare-versions "$latest_version" gt "$TAG"; then
            echo "Error: Found a newer version ($latest_version) than $TAG"
            exit 1
          fi
